# Generated by Django 5.0.4 on 2024-04-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_club_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
